import Head from 'next/head'
import { Suspense } from "react"
import { Canvas, useLoader } from "@react-three/fiber"
import { Environment, OrbitControls } from "@react-three/drei"
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"

const Model = () => {
  // location of the 3D model
  const gltf = useLoader(GLTFLoader, "/wolf/Wolf.gltf");
  const gltf2 = useLoader(GLTFLoader, "/spaceship/ship.gltf");
  return (
    <>
      {/* Use scale to control the size of the 3D model */}
      <primitive object={gltf.scene} scale={1.7} />
    </>
  );
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Three.js Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-3xl text-center mt-8 font-medium'>
        Welcome to my first 3D website
      </h1>
      <h2 className='text-lg text-center mt-2'>
      Just curiosity of how it works with 3D models and three.js :)
      </h2>

      <div className="globe">
        <Canvas shadows dpr={[1, 2]} camera={{ position: [0, 1, 4], fov: 40 }}>
          <ambientLight intensity={1} />
          <spotLight intensity={0.1} angle={0.1} penumbra={1} position={[10, 15, 10]} castShadow />
          <Suspense fallback={null}>
            <Model />
            {/* To add environment effect to the model */}
            <Environment preset="warehouse" />
            {/* <Environment preset="lobby" /> */}
            {/* <Environment preset="studio" /> */}
          </Suspense>
          <OrbitControls autoRotate />
        </Canvas>
      </div>

    </div>
  )
}